import { db } from "@/db";
import { users, strategies, botConfigs, trades, watchlists, backtests, notifications, aiConversations, exchangeKeys, priceAlerts, scanSchedules } from "@/db/schema";
import { eq } from "drizzle-orm";

export const DEMO_USER_ID = "user_demo_trader_01";

export async function seedDatabaseIfEmpty() {
  try {
    const existingUsers = await db.select().from(users).where(eq(users.id, DEMO_USER_ID)).limit(1);
    if (existingUsers.length > 0) {
      return { status: "already_seeded", user: existingUsers[0] };
    }

    // 1. Create Default Users
    await db.insert(users).values([
      {
        id: DEMO_USER_ID,
        name: "Alex Vance",
        email: "alex.vance@nexustrader.ai",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        role: "pro_trader",
        traderType: "day_trader",
        balance: "58240.50",
        initialBalance: "50000.00",
        currency: "USD",
        riskMode: "moderate",
        maxDailyLoss: "2500.00",
        maxLeverage: 10,
        autoTradingEnabled: true,
        soundEffects: true,
        theme: "dark",
        apiKeySimulation: true,
      },
      {
        id: "user_elena_quant_02",
        name: "Elena Rostova",
        email: "elena.r@nexustrader.ai",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
        role: "quant_researcher",
        traderType: "quant",
        balance: "100000.00",
        initialBalance: "100000.00",
        currency: "USD",
        riskMode: "conservative",
        maxDailyLoss: "3000.00",
        maxLeverage: 5,
        autoTradingEnabled: true,
        soundEffects: true,
        theme: "dark",
        apiKeySimulation: true,
      },
      {
        id: "user_sarah_crypto_03",
        name: "Sarah Chen",
        email: "sarah.chen@nexustrader.ai",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        role: "crypto_scalper",
        traderType: "crypto",
        balance: "25000.00",
        initialBalance: "25000.00",
        currency: "USD",
        riskMode: "aggressive",
        maxDailyLoss: "1500.00",
        maxLeverage: 20,
        autoTradingEnabled: true,
        soundEffects: false,
        theme: "dark",
        apiKeySimulation: true,
      },
    ]);

    // 2. Create Built-in Trending Strategies
    const defaultStrategies = [
      {
        id: "strat_breakout_momentum",
        userId: DEMO_USER_ID,
        name: "Breakout Momentum AI",
        description: "Identifies 20-period Donchian highs and resistance channel breaks with ADX > 25 trend confirmation and 200 EMA trend filtering.",
        category: "breakout",
        traderTypeMatch: "day_trader",
        timeframes: ["15m", "1h", "4h"],
        indicators: { donchianPeriod: 20, adxThreshold: 25, emaFilter: 200, volumeMultiplier: 1.6 },
        targetAssets: ["BTC/USDT", "SOL/USDT", "NVDA", "ETH/USDT"],
        weight: 35,
        minConfidence: 75,
        stopLossPercent: "2.20",
        takeProfitPercent: "6.00",
        trailingStop: true,
        isActive: true,
        winRate: "72.40",
        totalTradesCount: 148,
        profitFactor: "2.85",
        isCustom: false,
      },
      {
        id: "strat_macd_ema_surge",
        userId: DEMO_USER_ID,
        name: "Multi-Timeframe MACD & EMA Surge",
        description: "Algorithmic fast (9/21) EMA cross confirmed on multi-timeframes with MACD histogram expansion above zero line.",
        category: "momentum",
        traderTypeMatch: "all",
        timeframes: ["5m", "15m", "1h"],
        indicators: { fastEma: 9, slowEma: 21, trendEma: 200, macdFast: 12, macdSlow: 26, signalPeriod: 9 },
        targetAssets: ["BTC/USDT", "ETH/USDT", "NVDA", "TSLA", "XAU/USD"],
        weight: 30,
        minConfidence: 70,
        stopLossPercent: "1.80",
        takeProfitPercent: "5.20",
        trailingStop: true,
        isActive: true,
        winRate: "68.20",
        totalTradesCount: 212,
        profitFactor: "2.40",
        isCustom: false,
      },
      {
        id: "strat_smart_money_flow",
        userId: DEMO_USER_ID,
        name: "Smart Money & Liquidity Sweep (Order Flow AI)",
        description: "Scans for institutional stop runs, fair value gap (FVG) retests, and VWAP bounce confirmation with delta volume surges.",
        category: "smart_money",
        traderTypeMatch: "scalper",
        timeframes: ["5m", "15m", "1h"],
        indicators: { vwapBands: true, fvgLookback: 15, deltaThreshold: 1.8, liquidityPoolPeriod: 50 },
        targetAssets: ["BTC/USDT", "SOL/USDT", "XAU/USD", "EUR/USD"],
        weight: 25,
        minConfidence: 80,
        stopLossPercent: "1.50",
        takeProfitPercent: "4.80",
        trailingStop: true,
        isActive: true,
        winRate: "74.80",
        totalTradesCount: 184,
        profitFactor: "3.10",
        isCustom: false,
      },
      {
        id: "strat_neural_trend_pulse",
        userId: DEMO_USER_ID,
        name: "Deep AI Trend Pulse (Neural Ensemble)",
        description: "Combines 14 multi-timeframe oscillators, order book imbalances, and continuous NLP sentiment into a unified predictive vector.",
        category: "ml_ai",
        traderTypeMatch: "quant",
        timeframes: ["15m", "1h", "4h", "1D"],
        indicators: { model: "Transformer-TrendNet-v4", featureCount: 14, confidenceThreshold: 80 },
        targetAssets: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "NVDA", "AMD", "SUI/USDT"],
        weight: 40,
        minConfidence: 85,
        stopLossPercent: "2.50",
        takeProfitPercent: "7.50",
        trailingStop: true,
        isActive: true,
        winRate: "76.10",
        totalTradesCount: 320,
        profitFactor: "3.25",
        isCustom: false,
      },
      {
        id: "strat_bb_squeeze_volatility",
        userId: DEMO_USER_ID,
        name: "Bollinger Squeeze & Volatility Expansion",
        description: "Detects historical standard deviation compression inside Keltner Channels followed by explosive directional expansion.",
        category: "breakout",
        traderTypeMatch: "swing_trader",
        timeframes: ["1h", "4h", "1D"],
        indicators: { bbPeriod: 20, bbStdDev: 2.0, keltnerPeriod: 20, squeezeThreshold: 0.75 },
        targetAssets: ["NVDA", "TSLA", "SOL/USDT", "AVAX/USDT"],
        weight: 20,
        minConfidence: 75,
        stopLossPercent: "2.00",
        takeProfitPercent: "6.50",
        trailingStop: true,
        isActive: true,
        winRate: "65.50",
        totalTradesCount: 96,
        profitFactor: "2.15",
        isCustom: false,
      },
      {
        id: "strat_golden_fib_reversal",
        userId: DEMO_USER_ID,
        name: "Golden Pocket Fibonacci Reversion",
        description: "Buys precision 0.618 - 0.650 Fibonacci pullbacks within confirmed higher timeframe bullish structural trends.",
        category: "mean_reversion",
        traderTypeMatch: "swing_trader",
        timeframes: ["1h", "4h"],
        indicators: { fibLevels: [0.618, 0.65], swingLookback: 100, rsiOversold: 38 },
        targetAssets: ["BTC/USDT", "ETH/USDT", "XAU/USD"],
        weight: 25,
        minConfidence: 78,
        stopLossPercent: "1.90",
        takeProfitPercent: "5.80",
        trailingStop: false,
        isActive: false,
        winRate: "69.50",
        totalTradesCount: 110,
        profitFactor: "2.50",
        isCustom: false,
      },
    ];

    await db.insert(strategies).values(defaultStrategies);

    // 3. Create Default Bot Config
    const defaultBotId = "bot_nexus_alpha_01";
    await db.insert(botConfigs).values([
      {
        id: defaultBotId,
        userId: DEMO_USER_ID,
        name: "Nexus Alpha Autonomous Bot",
        isActive: true,
        selectedStrategyIds: [
          { strategyId: "strat_breakout_momentum", weight: 35 },
          { strategyId: "strat_macd_ema_surge", weight: 30 },
          { strategyId: "strat_neural_trend_pulse", weight: 35 },
        ],
        confluenceThreshold: 75,
        tradeAllocationType: "percent",
        tradeAllocationValue: "6.00",
        maxOpenTrades: 4,
        allowedMarkets: ["crypto", "stocks", "forex"],
        executionMode: "autonomous",
        defaultLeverage: 8,
        totalBotTrades: 42,
        botPnl: "8240.50",
      },
    ]);

    // 4. Create Active & Closed Demo Trades
    await db.insert(trades).values([
      {
        id: "trade_btc_active_01",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "BTC/USDT",
        market: "crypto",
        type: "BUY",
        status: "OPEN",
        entryPrice: "88200.0000",
        currentPrice: "89450.0000",
        quantity: "0.051020",
        amount: "4500.00",
        leverage: 10,
        stopLoss: "86500.0000",
        takeProfit: "92500.0000",
        trailingStop: true,
        trailingDistance: "1.80",
        pnl: "637.75",
        pnlPercent: "14.17",
        strategyUsed: "Multi-Strategy Confluence: Breakout Momentum + Neural Trend Pulse",
        strategyConfluence: [
          { name: "Breakout Momentum AI", weight: 35, signal: "BUY", score: 94 },
          { name: "Deep AI Trend Pulse", weight: 35, signal: "BUY", score: 92 },
          { name: "MACD & EMA Surge", weight: 30, signal: "BUY", score: 88 },
        ],
        aiConfidence: 94,
        aiReasoning: "Triple confluence breakout above $88,000 psychological resistance with strong Spot Delta absorption and 4h EMA golden alignment.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 6 * 3600 * 1000),
      },
      {
        id: "trade_sol_active_02",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "SOL/USDT",
        market: "crypto",
        type: "BUY",
        status: "OPEN",
        entryPrice: "192.4000",
        currentPrice: "198.8000",
        quantity: "15.592500",
        amount: "3000.00",
        leverage: 8,
        stopLoss: "187.0000",
        takeProfit: "210.0000",
        trailingStop: true,
        trailingDistance: "2.00",
        pnl: "798.33",
        pnlPercent: "26.61",
        strategyUsed: "Deep AI Trend Pulse + Smart Money Flow",
        strategyConfluence: [
          { name: "Deep AI Trend Pulse", weight: 50, signal: "BUY", score: 96 },
          { name: "Smart Money & Liquidity", weight: 50, signal: "BUY", score: 91 },
        ],
        aiConfidence: 96,
        aiReasoning: "Solana reclaimed $190 VWAP on high volume with ecosystem DEX volume surge and RSI 68 momentum acceleration.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 14 * 3600 * 1000),
      },
      {
        id: "trade_nvda_active_03",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "NVDA",
        market: "stocks",
        type: "BUY",
        status: "OPEN",
        entryPrice: "135.2000",
        currentPrice: "138.6500",
        quantity: "29.585700",
        amount: "4000.00",
        leverage: 3,
        stopLoss: "132.0000",
        takeProfit: "145.0000",
        trailingStop: true,
        trailingDistance: "2.50",
        pnl: "306.21",
        pnlPercent: "7.65",
        strategyUsed: "Multi-Timeframe MACD & EMA Surge",
        strategyConfluence: [
          { name: "MACD & EMA Surge", weight: 60, signal: "BUY", score: 89 },
          { name: "Breakout Momentum AI", weight: 40, signal: "BUY", score: 85 },
        ],
        aiConfidence: 88,
        aiReasoning: "NVDA breakout above previous 5-day channel with positive AI chip capex sentiment and daily EMA 20 bounce.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 28 * 3600 * 1000),
      },
      {
        id: "trade_xau_active_04",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "XAU/USD",
        market: "forex",
        type: "BUY",
        status: "OPEN",
        entryPrice: "2735.0000",
        currentPrice: "2748.6000",
        quantity: "1.828100",
        amount: "5000.00",
        leverage: 20,
        stopLoss: "2718.0000",
        takeProfit: "2775.0000",
        trailingStop: true,
        trailingDistance: "1.20",
        pnl: "497.25",
        pnlPercent: "9.94",
        strategyUsed: "Smart Money & Liquidity Sweep (Order Flow AI)",
        strategyConfluence: [
          { name: "Smart Money & Liquidity", weight: 60, signal: "BUY", score: 92 },
          { name: "Breakout Momentum AI", weight: 40, signal: "BUY", score: 88 },
        ],
        aiConfidence: 91,
        aiReasoning: "Gold swept liquidity below $2730 session low, formed strong bullish pinbar, and crossed dynamic 50-EMA.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 8 * 3600 * 1000),
      },
      // Closed Trades
      {
        id: "trade_eth_closed_05",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "ETH/USDT",
        market: "crypto",
        type: "BUY",
        status: "CLOSED",
        entryPrice: "3240.0000",
        exitPrice: "3420.0000",
        currentPrice: "3420.5000",
        quantity: "1.080200",
        amount: "3500.00",
        leverage: 8,
        stopLoss: "3180.0000",
        takeProfit: "3420.0000",
        trailingStop: false,
        pnl: "1555.55",
        pnlPercent: "44.44",
        strategyUsed: "Breakout Momentum AI + Neural Trend Pulse",
        aiConfidence: 91,
        aiReasoning: "Take-Profit target TP2 reached cleanly at $3,420 key resistance.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 48 * 3600 * 1000),
        exitTime: new Date(Date.now() - 4 * 3600 * 1000),
        closeReason: "take_profit",
        notes: "Full TP2 filled. +44.4% return on position margin.",
      },
      {
        id: "trade_sui_closed_06",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "SUI/USDT",
        market: "crypto",
        type: "BUY",
        status: "CLOSED",
        entryPrice: "2.6500",
        exitPrice: "3.0800",
        currentPrice: "3.1800",
        quantity: "754.716900",
        amount: "2000.00",
        leverage: 6,
        stopLoss: "2.5200",
        takeProfit: "3.0800",
        trailingStop: true,
        pnl: "973.58",
        pnlPercent: "48.68",
        strategyUsed: "Deep AI Trend Pulse",
        aiConfidence: 95,
        aiReasoning: "High-momentum L1 breakout confirmed by on-chain TVL surge.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 72 * 3600 * 1000),
        exitTime: new Date(Date.now() - 18 * 3600 * 1000),
        closeReason: "take_profit",
        notes: "AI Trailing stop closed trade locked in +48.68%.",
      },
      {
        id: "trade_tsla_closed_07",
        userId: DEMO_USER_ID,
        botConfigId: defaultBotId,
        symbol: "TSLA",
        market: "stocks",
        type: "BUY",
        status: "CLOSED",
        entryPrice: "254.0000",
        exitPrice: "248.0000",
        currentPrice: "248.3000",
        quantity: "11.811000",
        amount: "3000.00",
        leverage: 3,
        stopLoss: "248.0000",
        takeProfit: "268.0000",
        trailingStop: false,
        pnl: "-212.60",
        pnlPercent: "-7.08",
        strategyUsed: "Bollinger Squeeze & Volatility Expansion",
        aiConfidence: 74,
        aiReasoning: "Stop loss triggered at $248.00 after false squeeze breakout.",
        executionType: "ai_autonomous",
        entryTime: new Date(Date.now() - 96 * 3600 * 1000),
        exitTime: new Date(Date.now() - 60 * 3600 * 1000),
        closeReason: "stop_loss",
        notes: "Disciplined risk management kept loss contained under 2.5% account impact.",
      },
    ]);

    // 5. Watchlist Seed
    await db.insert(watchlists).values([
      {
        id: "wl_btc",
        userId: DEMO_USER_ID,
        symbol: "BTC/USDT",
        name: "Bitcoin",
        market: "crypto",
        alertHigh: "92000.00",
        alertLow: "87000.00",
        aiSentiment: "BULLISH",
        aiScore: 94,
        favorite: true,
      },
      {
        id: "wl_eth",
        userId: DEMO_USER_ID,
        symbol: "ETH/USDT",
        name: "Ethereum",
        market: "crypto",
        alertHigh: "3600.00",
        alertLow: "3300.00",
        aiSentiment: "BULLISH",
        aiScore: 89,
        favorite: true,
      },
      {
        id: "wl_sol",
        userId: DEMO_USER_ID,
        symbol: "SOL/USDT",
        name: "Solana",
        market: "crypto",
        alertHigh: "215.00",
        alertLow: "185.00",
        aiSentiment: "BULLISH",
        aiScore: 96,
        favorite: true,
      },
      {
        id: "wl_nvda",
        userId: DEMO_USER_ID,
        symbol: "NVDA",
        name: "NVIDIA Corp",
        market: "stocks",
        alertHigh: "145.00",
        alertLow: "133.00",
        aiSentiment: "BULLISH",
        aiScore: 88,
        favorite: true,
      },
      {
        id: "wl_xau",
        userId: DEMO_USER_ID,
        symbol: "XAU/USD",
        name: "Gold Spot",
        market: "forex",
        alertHigh: "2780.00",
        alertLow: "2720.00",
        aiSentiment: "BULLISH",
        aiScore: 91,
        favorite: true,
      },
      {
        id: "wl_sui",
        userId: DEMO_USER_ID,
        symbol: "SUI/USDT",
        name: "Sui Network",
        market: "crypto",
        alertHigh: "3.50",
        alertLow: "2.90",
        aiSentiment: "BULLISH",
        aiScore: 97,
        favorite: false,
      },
    ]);

    // 6. Backtest Seed
    const equityDataBtc = [
      { date: "Day 1", equity: 10000, benchmark: 10000 },
      { date: "Day 15", equity: 11420, benchmark: 10300 },
      { date: "Day 30", equity: 12850, benchmark: 10800 },
      { date: "Day 45", equity: 12400, benchmark: 9900 },
      { date: "Day 60", equity: 14600, benchmark: 11200 },
      { date: "Day 75", equity: 16800, benchmark: 12100 },
      { date: "Day 90", equity: 18460, benchmark: 12900 },
    ];

    const tradeLogsBtc = [
      { id: "bt_1", type: "BUY", entryDate: "Oct 12", exitDate: "Oct 16", entryPrice: 62400, exitPrice: 66800, pnl: 705.12, pnlPercent: 7.05, reason: "TP2 Hit on Donchian Breakout" },
      { id: "bt_2", type: "BUY", entryDate: "Oct 20", exitDate: "Oct 22", entryPrice: 67100, exitPrice: 65900, pnl: -178.83, pnlPercent: -1.79, reason: "Stop Loss Triggered (False Break)" },
      { id: "bt_3", type: "BUY", entryDate: "Oct 25", exitDate: "Nov 02", entryPrice: 68500, exitPrice: 74200, pnl: 832.11, pnlPercent: 8.32, reason: "Trailed Stop Exit after +8.3%" },
      { id: "bt_4", type: "BUY", entryDate: "Nov 06", exitDate: "Nov 14", entryPrice: 75800, exitPrice: 84100, pnl: 1094.98, pnlPercent: 10.95, reason: "Deep Trend Pulse Multiplier Exit" },
      { id: "bt_5", type: "BUY", entryDate: "Nov 18", exitDate: "Nov 24", entryPrice: 85200, exitPrice: 89400, pnl: 492.95, pnlPercent: 4.93, reason: "TP1 Hit on Volatility Surge" },
    ];

    await db.insert(backtests).values([
      {
        id: "bt_btc_90d_confluence",
        userId: DEMO_USER_ID,
        name: "BTC/USDT Multi-Strategy Trend Engine (90D)",
        symbol: "BTC/USDT",
        timeframe: "1h",
        dateRange: "90d",
        strategyIds: ["strat_breakout_momentum", "strat_neural_trend_pulse", "strat_macd_ema_surge"],
        initialCapital: "10000.00",
        finalCapital: "18460.00",
        totalReturnPercent: "84.60",
        winRate: "71.40",
        profitFactor: "2.82",
        maxDrawdown: "6.80",
        sharpeRatio: "2.85",
        totalTrades: 28,
        winningTrades: 20,
        losingTrades: 8,
        equityCurve: equityDataBtc,
        tradeLogs: tradeLogsBtc,
      },
      {
        id: "bt_nvda_breakout",
        userId: DEMO_USER_ID,
        name: "NVDA AI Chip Breakout & Squeeze (90D)",
        symbol: "NVDA",
        timeframe: "4h",
        dateRange: "90d",
        strategyIds: ["strat_breakout_momentum", "strat_bb_squeeze_volatility"],
        initialCapital: "10000.00",
        finalCapital: "16230.00",
        totalReturnPercent: "62.30",
        winRate: "68.00",
        profitFactor: "2.45",
        maxDrawdown: "8.20",
        sharpeRatio: "2.45",
        totalTrades: 25,
        winningTrades: 17,
        losingTrades: 8,
        equityCurve: [
          { date: "Day 1", equity: 10000, benchmark: 10000 },
          { date: "Day 30", equity: 11900, benchmark: 10600 },
          { date: "Day 60", equity: 13800, benchmark: 11400 },
          { date: "Day 90", equity: 16230, benchmark: 12200 },
        ],
        tradeLogs: [
          { id: "bt_n1", type: "BUY", entryDate: "Sep 15", exitDate: "Sep 28", entryPrice: 116, exitPrice: 128, pnl: 1034.48, pnlPercent: 10.34, reason: "TP2 Reached" },
          { id: "bt_n2", type: "BUY", entryDate: "Oct 05", exitDate: "Oct 18", entryPrice: 124, exitPrice: 139, pnl: 1209.67, pnlPercent: 12.10, reason: "Squeeze Expansion Exit" },
        ],
      },
    ]);

    // 7. Notifications Seed
    await db.insert(notifications).values([
      {
        id: "notif_01",
        userId: DEMO_USER_ID,
        title: "🤖 AI Trade Auto-Executed",
        message: "Nexus Alpha Bot opened BUY on BTC/USDT at $88,200 (Confluence Score: 94/100).",
        type: "trade_executed",
        isRead: false,
        metadata: { symbol: "BTC/USDT", amount: 4500, leverage: 10 },
      },
      {
        id: "notif_02",
        userId: DEMO_USER_ID,
        title: "🎯 Take-Profit Target Hit",
        message: "ETH/USDT TP2 triggered at $3,420.00. Realized Net Profit: +$1,555.55 (+44.44%).",
        type: "tp_hit",
        isRead: false,
        metadata: { symbol: "ETH/USDT", pnl: 1555.55 },
      },
      {
        id: "notif_03",
        userId: DEMO_USER_ID,
        title: "🔥 High-Confluence Breakout Alert",
        message: "SOL/USDT triggered multi-strategy buy signal (96% Confidence) with 3.4x volume surge.",
        type: "ai_signal",
        isRead: true,
        metadata: { symbol: "SOL/USDT", score: 96 },
      },
      {
        id: "notif_04",
        userId: DEMO_USER_ID,
        title: "⚡ Market Scan Complete",
        message: "Automated scan of 12 markets complete: 4 Strong Buy signals detected, risk within safe parameters.",
        type: "system",
        isRead: true,
        metadata: { marketsScanned: 12 },
      },
    ]);

    // 8. AI Copilot Conversation Seed
    await db.insert(aiConversations).values([
      {
        id: "conv_default_01",
        userId: DEMO_USER_ID,
        title: "Bitcoin & Solana Momentum Setup Analysis",
        messages: [
          {
            id: "m_1",
            role: "user",
            content: "What trending strategies have the highest confluence on BTC and SOL right now?",
            timestamp: new Date(Date.now() - 3600 * 1000).toISOString(),
          },
          {
            id: "m_2",
            role: "assistant",
            content:
              "Based on real-time multi-timeframe analysis across 15m, 1h, and 4h charts:\n\n1. **BTC/USDT**: The **Breakout Momentum AI** (Score: 94) and **Deep AI Trend Pulse** (Score: 92) show strong confluence above the $88,000 psychological resistance. Order flow indicates heavy spot bidding with negative funding rate reset.\n2. **SOL/USDT**: **Deep AI Trend Pulse** (Score: 96) has triggered with high volume expansion. Current resistance target is $210 with invalidation below $187.\n\n*Recommendation*: The automated bot has already entered both positions with trailing stop safeguards enabled.",
            suggestedStrategy: {
              name: "Breakout Momentum + AI Pulse",
              target: "BTC & SOL",
              expectedWinRate: "73%",
            },
            timestamp: new Date(Date.now() - 3500 * 1000).toISOString(),
          },
        ],
      },
    ]);

    // 9. Demo Exchange Keys (pre-connected)
    await db.insert(exchangeKeys).values([
      {
        id: "exk_binance_demo",
        userId: DEMO_USER_ID,
        exchangeName: "binance",
        label: "Binance Futures (Testnet)",
        apiKey: "vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A",
        apiSecret: "NhqPtmdSJYdKjVHjA7PZj4Mge3R5YNiP1e3UZjInClVN65XAbvqqM6A7H5fATj0j",
        isTestnet: true,
        isActive: true,
        connectionStatus: "connected",
        lastPingMs: 14,
        lastConnectedAt: new Date(),
        permissions: ["read", "trade"],
        totalTradesViaKey: 42,
        totalVolume: "124850.00",
      },
      {
        id: "exk_alpaca_demo",
        userId: DEMO_USER_ID,
        exchangeName: "alpaca",
        label: "Alpaca Paper Trading",
        apiKey: "PKTA1AEFP2N3WZFXJZ5C",
        apiSecret: "pnq4YHlbMlLcksfU8KQE0LVlYOhR7kE0jQBxSLhF",
        isTestnet: true,
        isActive: true,
        connectionStatus: "connected",
        lastPingMs: 28,
        lastConnectedAt: new Date(),
        permissions: ["read", "trade"],
        totalTradesViaKey: 18,
        totalVolume: "45200.00",
      },
    ]);

    // 10. Demo Price Alerts
    await db.insert(priceAlerts).values([
      {
        id: "pa_btc_100k",
        userId: DEMO_USER_ID,
        symbol: "BTC/USDT",
        name: "BTC/USDT Above $95,000",
        market: "crypto",
        alertType: "price_above",
        targetValue: "95000.0000",
        currentValue: "89450.0000",
        condition: ">=",
        isActive: true,
        isTriggered: false,
        notificationChannels: ["in_app", "sound"],
        notes: "Major psychological resistance breakout",
      },
      {
        id: "pa_sol_breakout",
        userId: DEMO_USER_ID,
        symbol: "SOL/USDT",
        name: "SOL/USDT Above $215",
        market: "crypto",
        alertType: "price_above",
        targetValue: "215.0000",
        currentValue: "198.8000",
        condition: ">=",
        isActive: true,
        isTriggered: false,
        notificationChannels: ["in_app", "sound"],
      },
      {
        id: "pa_nvda_rsi",
        userId: DEMO_USER_ID,
        symbol: "NVDA",
        name: "NVDA RSI > 75",
        market: "stocks",
        alertType: "rsi_overbought",
        targetValue: "75.0000",
        currentValue: "61.8000",
        condition: ">=",
        isActive: true,
        isTriggered: false,
        notificationChannels: ["in_app", "sound"],
        notes: "Take partial profits if RSI enters overbought",
      },
      {
        id: "pa_xau_drop",
        userId: DEMO_USER_ID,
        symbol: "XAU/USD",
        name: "XAU/USD Below $2,720",
        market: "forex",
        alertType: "price_below",
        targetValue: "2720.0000",
        currentValue: "2748.6000",
        condition: "<=",
        isActive: true,
        isTriggered: false,
        notificationChannels: ["in_app", "sound"],
      },
    ]);

    // 11. Demo Scan Schedule
    await db.insert(scanSchedules).values([
      {
        id: "sched_default_crypto",
        userId: DEMO_USER_ID,
        name: "Crypto Momentum Scanner",
        isActive: true,
        intervalSeconds: 30,
        targetMarkets: ["crypto"],
        scanType: "confluence",
        minConfluenceScore: 80,
        autoExecute: false,
        totalScansRun: 284,
        totalSignalsFound: 42,
      },
      {
        id: "sched_all_markets_auto",
        userId: DEMO_USER_ID,
        name: "All Markets Auto-Trader",
        isActive: false,
        intervalSeconds: 60,
        targetMarkets: ["crypto", "stocks", "forex"],
        scanType: "confluence",
        minConfluenceScore: 85,
        autoExecute: true,
        totalScansRun: 156,
        totalSignalsFound: 18,
        totalAutoTrades: 7,
      },
    ]);

    console.log("Database seeded successfully!");
    return { status: "seeded" };
  } catch (error) {
    console.error("Error seeding database:", error);
    return { status: "error", error };
  }
}
